source 'https://rubygems.org'
ruby '2.1.2'

gem 'sinatra'
gem 'haml'
gem 'thin'
gem 'data_mapper'
gem 'dm-postgres-adapter'
gem 'bcrypt'
gem 'pony'
#gem 'omniauth'
gem 'omniauth-gplus'
gem 'warden'
gem 'russian'